# Generated by Django 3.2.4 on 2021-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
