# Generated by Django 3.2.4 on 2021-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
