# Generated by Django 3.2.4 on 2021-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_username_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='owner',
            field=models.BooleanField(null=True),
        ),
    ]
