# Generated by Django 3.2.4 on 2021-06-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatmessage_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
    ]
